"""add interview sharing fields

Revision ID: 55007501b0f4
Revises: 
Create Date: 2026-06-01 20:09:00.933158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55007501b0f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

