"""add_gap_bridge_tables

Revision ID: 902b185c90da
Revises: 1cc75f0afe76
Create Date: 2026-06-01 20:40:27.854885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902b185c90da'
down_revision = '1cc75f0afe76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

