"""add used_gemini to analyses

Revision ID: add_used_gemini_analyses
Revises: (autogenerated baseline)
Create Date: 2026-06-06

This migration is intentionally minimal: it adds the missing `used_gemini` column
required by app/models/analysis.py.
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_used_gemini_analyses'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        'analyses',
        sa.Column('used_gemini', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )


def downgrade() -> None:
    op.drop_column('analyses', 'used_gemini')

